// packages/solid/src/components/ai/AIStatus.jsx
import { Show, createMemo } from 'solid-js';

export default function AIStatus(props) {
  const statusConfig = createMemo(() => {
    switch (props.status) {
      case 'connected':
        return { label: 'Connected', color: 'var(--cn-success)', icon: '●' };
      case 'disconnected':
        return { label: 'Disconnected', color: 'var(--cn-error)', icon: '○' };
      case 'connecting':
        return { label: 'Connecting...', color: 'var(--cn-warning)', icon: '◐' };
      case 'error':
        return { label: 'Error', color: 'var(--cn-error)', icon: '✕' };
      case 'rate-limited':
        return { label: 'Rate limited', color: 'var(--cn-warning)', icon: '⏱' };
      case 'idle':
        return { label: 'Idle', color: 'var(--cn-text-tertiary)', icon: '◌' };
      default:
        return { label: 'Unknown', color: 'var(--cn-text-tertiary)', icon: '?' };
    }
  });

  return (
    <div 
      class="cn-ai-status"
      role="status"
      aria-label={`AI status: ${statusConfig().label}`}
    >
      <span 
        class="cn-ai-status-icon"
        style={{ color: statusConfig().color }}
      >
        {statusConfig().icon}
      </span>
      <span class="cn-ai-status-label">{statusConfig().label}</span>

      <Show when={props.latency !== undefined}>
        <span class="cn-ai-status-latency">
          {props.latency}ms
        </span>
      </Show>

      <Show when={props.model}>
        <span class="cn-ai-status-model">
          {props.model}
        </span>
      </Show>

      <style>{`
        .cn-ai-status {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          padding: 6px 12px;
          background: var(--cn-bg-secondary);
          border: 1px solid var(--cn-border-default);
          border-radius: 8px;
          font-size: 13px;
        }

        .cn-ai-status-icon {
          font-size: 10px;
        }

        .cn-ai-status-label {
          color: var(--cn-text-primary);
          font-weight: 500;
        }

        .cn-ai-status-latency {
          color: var(--cn-text-tertiary);
          font-size: 12px;
          font-variant-numeric: tabular-nums;
        }

        .cn-ai-status-model {
          color: var(--cn-text-secondary);
          font-size: 12px;
          padding-left: 8px;
          border-left: 1px solid var(--cn-border-default);
        }
      `}</style>
    </div>
  );
}

// packages/svelte/src/AIStatus.svelte
<script>
  /** @type {'idle' | 'generating' | 'streaming' | 'error' | 'rate-limited'} */
  export let status = 'idle';
  /** @type {string} */
  export let model = '';
  /** @type {string} */
  export let errorMessage = '';
  /** @type {number} */
  export let retryAfter = 0;

  const config = {
    idle: { label: 'Ready', color: 'success', icon: '●' },
    generating: { label: 'Generating', color: 'warning', icon: '◉' },
    streaming: { label: 'Streaming', color: 'info', icon: '◉' },
    error: { label: 'Error', color: 'error', icon: '✕' },
    'rate-limited': { label: 'Rate Limited', color: 'warning', icon: '◉' },
  };
</script>

<div
  class="cn-ai-status"
  class:cn-ai-status-success={config[status]?.color === 'success'}
  class:cn-ai-status-warning={config[status]?.color === 'warning'}
  class:cn-ai-status-error={config[status]?.color === 'error'}
  class:cn-ai-status-info={config[status]?.color === 'info'}
  role="status"
  aria-live="polite"
>
  <span
    class="cn-ai-status-dot"
    class:cn-ai-status-pulse={status === 'generating' || status === 'streaming'}
  >{config[status]?.icon || '●'}</span>
  <span class="cn-ai-status-label">{config[status]?.label || 'Unknown'}</span>
  {#if model}
    <span class="cn-ai-status-model">{model}</span>
  {/if}
  {#if status === 'error' && errorMessage}
    <span class="cn-ai-status-error-msg">{errorMessage}</span>
  {/if}
  {#if status === 'rate-limited' && retryAfter}
    <span class="cn-ai-status-retry">Retry in {retryAfter}s</span>
  {/if}
</div>

<style>
  .cn-ai-status { display: flex; align-items: center; gap: 6px; font-size: 13px; padding: 4px 10px; border-radius: var(--cn-radius); }
  .cn-ai-status-success { color: var(--cn-success); }
  .cn-ai-status-warning { color: var(--cn-warning); }
  .cn-ai-status-error { color: var(--cn-error); }
  .cn-ai-status-info { color: var(--cn-info); }
  .cn-ai-status-pulse { animation: cn-pulse 1.5s ease-in-out infinite; }
  .cn-ai-status-model { font-size: 11px; opacity: 0.7; }
  .cn-ai-status-error-msg { font-size: 12px; color: var(--cn-error); }
  .cn-ai-status-retry { font-size: 12px; }
  @keyframes cn-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
</style>
