// packages/solid/src/components/Breadcrumb.jsx
import { mergeProps, For, Show } from 'solid-js';

export function Breadcrumb(props) {
  const merged = mergeProps({
    items: [],
    separator: '/'
  }, props);

  return (
    <nav class="cn-breadcrumb">
      <For each={merged.items}>{(item, index) => (
        <>
          <Show when={index() > 0}>
            <span class="cn-breadcrumb-separator">{merged.separator}</span>
          </Show>
          <a
            class={`cn-breadcrumb-item ${index() === merged.items.length - 1 ? 'cn-breadcrumb-item-current' : ''}`}
            href={item.href || '#'}
            onClick={(e) => {
              if (item.onClick) {
                e.preventDefault();
                item.onClick();
              }
            }}
          >
            {item.label}
          </a>
        </>
      )}</For>
    </nav>
  );
}

// packages/svelte/src/Breadcrumb.svelte
<script>
	export let items = [];
	export let separator = '/';
</script>

<nav class="cn-breadcrumb">
	{#each items as item, i}
		{#if i > 0}
			<span class="cn-breadcrumb-separator">{separator}</span>
		{/if}
		{#if i === items.length - 1}
			<span class="cn-breadcrumb-current">{item.label}</span>
		{:else}
			<a href={item.href} class="cn-breadcrumb-item">{item.label}</a>
		{/if}
	{/each}
</nav>

<style>
	.cn-breadcrumb {
		display: flex;
		align-items: center;
		gap: 8px;
		font-size: 12px;
	}
	.cn-breadcrumb-item {
		color: rgba(240, 237, 232, 0.5);
		text-decoration: none;
		transition: color 0.15s ease;
	}
	.cn-breadcrumb-item:hover {
		color: #f0ede8;
	}
	.cn-breadcrumb-separator {
		color: rgba(240, 237, 232, 0.25);
	}
	.cn-breadcrumb-current {
		color: #f0ede8;
	}
</style>
