// packages/solid/src/components/ai/ChatInterface.jsx
import { createSignal, For, Show, onMount, onCleanup } from 'solid-js';
import MessageBubble from './MessageBubble';
import PromptInput from './PromptInput';
import TypingIndicator from './TypingIndicator';

export default function ChatInterface(props) {
  const [messages, setMessages] = createSignal(props.messages || []);
  const [isTyping, setIsTyping] = createSignal(false);
  let messagesEndRef;

  const scrollToBottom = () => {
    messagesEndRef?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleSend = async (content) => {
    const userMessage = {
      id: Date.now(),
      role: 'user',
      content,
      timestamp: new Date().toISOString()
    };
    setMessages(prev => [...prev, userMessage]);
    props.onSend?.(userMessage);

    setIsTyping(true);
  };

  const addAssistantMessage = (content) => {
    const assistantMessage = {
      id: Date.now(),
      role: 'assistant',
      content,
      timestamp: new Date().toISOString()
    };
    setMessages(prev => [...prev, assistantMessage]);
    setIsTyping(false);
  };

  const handleError = (error) => {
    setIsTyping(false);
    props.onError?.(error);
  };

  onMount(() => {
    scrollToBottom();
  });

  return (
    <div 
      class="cn-chat-interface"
      role="log"
      aria-label="Chat conversation"
      aria-live="polite"
    >
      <div class="cn-chat-messages" role="list">
        <For each={messages()}>
          {(message) => (
            <div role="listitem">
              <MessageBubble
                role={message.role}
                content={message.content}
                timestamp={message.timestamp}
                avatar={message.avatar}
                status={message.status}
              />
            </div>
          )}
        </For>
        <Show when={isTyping()}>
          <TypingIndicator avatar={props.assistantAvatar} />
        </Show>
        <div ref={messagesEndRef} />
      </div>

      <div class="cn-chat-footer">
        <PromptInput
          onSend={handleSend}
          disabled={isTyping()}
          placeholder={props.placeholder || 'Type a message...'}
          maxLength={props.maxInputLength}
        />
      </div>

      <style>{`
        .cn-chat-interface {
          display: flex;
          flex-direction: column;
          height: 100%;
          max-height: 100vh;
          background: var(--cn-bg-primary);
          border: 1px solid var(--cn-border-default);
          border-radius: 12px;
          overflow: hidden;
        }

        .cn-chat-messages {
          flex: 1;
          overflow-y: auto;
          padding: 16px;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .cn-chat-footer {
          padding: 16px;
          border-top: 1px solid var(--cn-border-default);
          background: var(--cn-bg-secondary);
        }
      `}</style>
    </div>
  );
}

// packages/svelte/src/ChatInterface.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import MessageBubble from './MessageBubble.svelte';
  import TypingIndicator from './TypingIndicator.svelte';
  import PromptInput from './PromptInput.svelte';

  /** @type {Array<{id: string, role: 'user'|'assistant', content: string, timestamp: Date}>} */
  export let messages = [];
  /** @type {boolean} */
  export let loading = false;
  /** @type {string} */
  export let placeholder = 'Ask AI anything...';

  const dispatch = createEventDispatcher();

  function handleSend(event) {
    dispatch('send', event.detail);
  }
</script>

<div class="cn-chat-interface">
  <div class="cn-chat-header">
    <h2 class="cn-chat-title">Chat</h2>
    {#if loading}
      <TypingIndicator show={true} label="Thinking..." />
    {/if}
  </div>

  <div class="cn-chat-messages" role="log" aria-live="polite">
    {#each messages as msg (msg.id)}
      <MessageBubble role={msg.role} content={msg.content} timestamp={msg.timestamp} />
    {/each}
  </div>

  <div class="cn-chat-input-container">
    <PromptInput {loading} {placeholder} on:submit={handleSend} />
  </div>
</div>

<style>
  .cn-chat-interface {
    display: flex;
    flex-direction: column;
    height: 100%;
    border: 1px solid var(--cn-border);
    border-radius: var(--cn-radius-lg);
    overflow: hidden;
  }
  .cn-chat-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 16px;
    border-bottom: 1px solid var(--cn-border);
    background: var(--cn-surface);
  }
  .cn-chat-title {
    margin: 0;
    font-size: 16px;
  }
  .cn-chat-messages {
    flex: 1;
    overflow-y: auto;
    padding: 16px;
  }
  .cn-chat-input-container {
    padding: 12px;
    border-top: 1px solid var(--cn-border);
  }
</style>
