// packages/solid/src/components/ai/MarkdownRenderer.jsx
import { createMemo } from 'solid-js';

function parseMarkdown(text) {
  let html = text;

  // Code blocks (```...```)
  html = html.replace(/```(\w+)?\n([\s\S]*?)```/g, (_, lang, code) => {
    const language = lang || 'text';
    return `<pre class="cn-md-code-block"><div class="cn-md-code-lang">${language}</div><code>${escapeHtml(code.trim())}</code></pre>`;
  });

  // Inline code
  html = html.replace(/`([^`]+)`/g, '<code class="cn-md-inline-code">$1</code>');

  // Headers
  html = html.replace(/^### (.+)$/gm, '<h3 class="cn-md-h3">$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2 class="cn-md-h2">$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1 class="cn-md-h1">$1</h1>');

  // Bold and italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Links
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a class="cn-md-link" href="$2" target="_blank" rel="noopener">$1</a>');

  // Images
  html = html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img class="cn-md-image" src="$2" alt="$1" />');

  // Blockquotes
  html = html.replace(/^> (.+)$/gm, '<blockquote class="cn-md-blockquote">$1</blockquote>');

  // Unordered lists
  html = html.replace(/^\-\* (.+)$/gm, '<li class="cn-md-list-item">$1</li>');
  html = html.replace(/((?:<li class="cn-md-list-item">.*<\/li>\n?)+)/g, '<ul class="cn-md-list">$1</ul>');

  // Ordered lists
  html = html.replace(/^\d+\. (.+)$/gm, '<li class="cn-md-list-item-ordered">$1</li>');
  html = html.replace(/((?:<li class="cn-md-list-item-ordered">.*<\/li>\n?)+)/g, '<ol class="cn-md-list-ordered">$1</ol>');

  // Tables
  html = html.replace(/\|(.+)\|\n\|[-| ]+\|\n((?:\|.+\|\n?)+)/g, (_, header, rows) => {
    const headers = header.split('|').filter(Boolean).map(h => `<th class="cn-md-table-th">${h.trim()}</th>`).join('');
    const rowsHtml = rows.trim().split('\n').map(row => {
      const cells = row.split('|').filter(Boolean).map(c => `<td class="cn-md-table-td">${c.trim()}</td>`).join('');
      return `<tr>${cells}</tr>`;
    }).join('');
    return `<table class="cn-md-table"><thead><tr>${headers}</tr></thead><tbody>${rowsHtml}</tbody></table>`;
  });

  // Horizontal rule
  html = html.replace(/^---$/gm, '<hr class="cn-md-hr" />');

  // Paragraphs (lines that aren't already wrapped)
  html = html.replace(/^(?!<[a-z/])((?!^$).+)$/gm, '<p class="cn-md-paragraph">$1</p>');

  // Line breaks
  html = html.replace(/\n\n/g, '\n');

  return html;
}

function escapeHtml(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export function MarkdownRenderer(props) {
  const html = createMemo(() => parseMarkdown(props.content || ''));

  return (
    <div
      class={props.className ? `cn-markdown-renderer ${props.className}` : 'cn-markdown-renderer'}
      role="document"
      aria-label="Markdown content"
      innerHTML={html()}
    />
  );
}

// packages/svelte/src/MarkdownRenderer.svelte
<script>
  /** @type {string} */
  export let content = '';

  function escapeHtml(text) {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function parseMarkdown(text) {
    let html = text;
    html = html.replace(/```(\w+)?\n([\s\S]*?)```/g, (_, lang, code) => {
      const language = lang || 'text';
      return `<pre class="cn-md-code-block"><div class="cn-md-code-lang">${language}</div><code>${escapeHtml(code.trim())}</code></pre>`;
    });
    html = html.replace(/`([^`]+)`/g, '<code class="cn-md-inline-code">$1</code>');
    html = html.replace(/^### (.+)$/gm, '<h3 class="cn-md-h3">$1</h3>');
    html = html.replace(/^## (.+)$/gm, '<h2 class="cn-md-h2">$1</h2>');
    html = html.replace(/^# (.+)$/gm, '<h1 class="cn-md-h1">$1</h1>');
    html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
    html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a class="cn-md-link" href="$2" target="_blank" rel="noopener">$1</a>');
    html = html.replace(/^> (.+)$/gm, '<blockquote class="cn-md-blockquote">$1</blockquote>');
    html = html.replace(/^[\-\*] (.+)$/gm, '<li class="cn-md-list-item">$1</li>');
    html = html.replace(/((?:<li class="cn-md-list-item">.*<\/li>\n?)+)/g, '<ul class="cn-md-list">$1</ul>');
    html = html.replace(/^\d+\. (.+)$/gm, '<li class="cn-md-list-item-ordered">$1</li>');
    html = html.replace(/((?:<li class="cn-md-list-item-ordered">.*<\/li>\n?)+)/g, '<ol class="cn-md-list-ordered">$1</ol>');
    html = html.replace(/^---$/gm, '<hr class="cn-md-hr" />');
    html = html.replace(/^(?!<[a-z/])((?!^$).+)$/gm, '<p class="cn-md-paragraph">$1</p>');
    return html;
  }

  $: html = parseMarkdown(content);
</script>

<div class="cn-markdown-renderer">
  {@html html}
</div>

<style>
  .cn-markdown-renderer { line-height: 1.6; }
  :global(.cn-md-h1) { font-size: 1.5em; margin: 0.5em 0; font-weight: 600; }
  :global(.cn-md-h2) { font-size: 1.3em; margin: 0.5em 0; font-weight: 600; }
  :global(.cn-md-h3) { font-size: 1.1em; margin: 0.5em 0; font-weight: 600; }
  :global(.cn-md-inline-code) { background: var(--cn-surface-2); padding: 2px 6px; border-radius: var(--cn-radius); font-family: monospace; font-size: 0.9em; }
  :global(.cn-md-code-block) { background: var(--cn-code-bg, #1e1e1e); border-radius: var(--cn-radius); overflow: auto; margin: 1em 0; padding: 12px; font-family: monospace; font-size: 13px; }
  :global(.cn-md-blockquote) { border-left: 3px solid var(--cn-primary); padding-left: 12px; margin: 0.5em 0; color: var(--cn-text-muted); }
  :global(.cn-md-link) { color: var(--cn-primary); text-decoration: underline; }
  :global(.cn-md-list), :global(.cn-md-list-ordered) { padding-left: 1.5em; margin: 0.5em 0; }
  :global(.cn-md-list-item), :global(.cn-md-list-item-ordered) { margin: 0.25em 0; }
  :global(.cn-md-paragraph) { margin: 0.5em 0; }
  :global(.cn-md-hr) { border: none; border-top: 1px solid var(--cn-border); margin: 1em 0; }
</style>
