// packages/react/src/components/ai/PromptInput.tsx
import React, { useState, useRef, useEffect } from 'react';
import { cn } from '../../utils/cn';
import { ModelSelector, ModelOption } from './ModelSelector';
import { TokenCounter } from './TokenCounter';

export interface PromptInputProps {
  onSubmit?: (prompt: string, model?: string) => void;
  models?: ModelOption[];
  selectedModel?: string;
  onModelChange?: (modelId: string) => void;
  placeholder?: string;
  disabled?: boolean;
  loading?: boolean;
  maxLength?: number;
  showTokenCount?: boolean;
  className?: string;
}

export const PromptInput: React.FC<PromptInputProps> = ({
  onSubmit,
  models,
  selectedModel,
  onModelChange,
  placeholder = 'Ask AI anything...',
  disabled = false,
  loading = false,
  maxLength = 10000,
  showTokenCount = false,
  className,
}) => {
  const [prompt, setPrompt] = useState('');
  const [tokenEstimate, setTokenEstimate] = useState(0);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Simple token estimation (roughly 4 chars per token)
  useEffect(() => {
    setTokenEstimate(Math.ceil(prompt.length / 4));
  }, [prompt]);

  const handleSubmit = () => {
    if (!prompt.trim() || disabled || loading) return;
    onSubmit?.(prompt, selectedModel);
    setPrompt('');
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  // Auto-resize textarea
  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const textarea = e.target;
    textarea.style.height = 'auto';
    textarea.style.height = `${Math.min(textarea.scrollHeight, 200)}px`;
    setPrompt(textarea.value);
  };

  return (
    <div className={cn('cn-prompt-input', className)}>
      <div className="cn-prompt-input-toolbar">
        {models && models.length > 0 && (
          <ModelSelector
            models={models}
            value={selectedModel || ''}
            onChange={onModelChange || (() => {})}
            placeholder="Select model"
          />
        )}
      </div>

      <div className="cn-prompt-input-main">
        <textarea
          ref={textareaRef}
          className="cn-prompt-textarea"
          placeholder={placeholder}
          value={prompt}
          onChange={handleInput}
          onKeyDown={handleKeyDown}
          disabled={disabled || loading}
          maxLength={maxLength}
          rows={1}
          aria-label="AI prompt input"
        />
        <button
          className={cn('cn-prompt-submit', (!prompt.trim() || disabled || loading) && 'cn-prompt-submit-disabled')}
          onClick={handleSubmit}
          disabled={!prompt.trim() || disabled || loading}
          aria-label="Send prompt"
        >
          {loading ? (
            <span className="cn-prompt-loading">
              <span className="cn-spinner-small" />
            </span>
          ) : (
            <span className="cn-prompt-send-icon">↑</span>
          )}
        </button>
      </div>

      <div className="cn-prompt-footer">
        <span className="cn-prompt-hint">
          Press Enter to send · Shift+Enter for new line
        </span>
        {showTokenCount && (
          <TokenCounter
            promptTokens={tokenEstimate}
            completionTokens={0}
            showBreakdown={false}
          />
        )}
      </div>
    </div>
  );
};

// packages/svelte/src/PromptInput.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  /** @type {string} */
  export let placeholder = 'Ask AI anything...';
  /** @type {boolean} */
  export let loading = false;

  const dispatch = createEventDispatcher();
  let prompt = '';

  function handleSubmit() {
    if (!prompt.trim() || loading) return;
    dispatch('submit', { prompt });
    prompt = '';
  }

  function handleKeydown(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  }
</script>

<div class="cn-prompt-input">
  <div class="cn-prompt-input-main">
    <textarea
      class="cn-prompt-textarea"
      {placeholder}
      bind:value={prompt}
      on:keydown={handleKeydown}
      disabled={loading}
      rows="1"
      aria-label="AI prompt input"
    />
    <button
      class="cn-prompt-submit"
      class:cn-prompt-submit-disabled={!prompt.trim() || loading}
      on:click={handleSubmit}
      disabled={!prompt.trim() || loading}
      aria-label="Send prompt"
    >
      {#if loading}
        <span class="cn-spinner-small">⏳</span>
      {:else}
        <span class="cn-prompt-send-icon">↑</span>
      {/if}
    </button>
  </div>
  <div class="cn-prompt-footer">
    <span class="cn-prompt-hint">Press Enter to send · Shift+Enter for new line</span>
  </div>
</div>

<style>
  .cn-prompt-input {
    border: 1px solid var(--cn-border);
    border-radius: var(--cn-radius-lg);
    background: var(--cn-surface);
  }
  .cn-prompt-input-main {
    display: flex;
    align-items: flex-end;
    padding: 12px;
    gap: 8px;
  }
  .cn-prompt-textarea {
    flex: 1;
    border: none;
    background: transparent;
    resize: none;
    font-size: 14px;
    line-height: 1.5;
    font-family: inherit;
    outline: none;
  }
  .cn-prompt-submit {
    width: 36px;
    height: 36px;
    border-radius: 50%;
    background: var(--cn-primary);
    color: var(--cn-on-primary, #fff);
    border: none;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    transition: all 0.2s ease;
  }
  .cn-prompt-submit:hover { opacity: 0.9; transform: scale(1.05); }
  .cn-prompt-submit-disabled { opacity: 0.4; cursor: not-allowed; }
  .cn-prompt-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 8px 12px;
    border-top: 1px solid var(--cn-border);
    font-size: 12px;
    color: var(--cn-text-muted);
  }
</style>
