// packages/react/src/components/Timeline.tsx
import * as React from 'react';

export interface TimelineItem {
  title: string;
  description?: string;
  timestamp?: string;
  icon?: React.ReactNode;
  variant?: 'default' | 'success' | 'warning' | 'error' | 'info';
}

export interface TimelineProps extends React.HTMLAttributes<HTMLDivElement> {
  items: TimelineItem[];
}

export const Timeline: React.FC<TimelineProps> = ({
  items,
  className = '',
  ...props
}) => {
  return (
    <div className={`cn-timeline ${className}`.trim()} {...props}>
      {items.map((item, index) => (
        <div
          key={index}
          className={`cn-timeline-item ${item.variant || 'default'}`}
        >
          <div className="cn-timeline-connector">
            <div className="cn-timeline-dot">
              {item.icon || <span className="cn-timeline-dot-inner" />}
            </div>
            {index < items.length - 1 && <div className="cn-timeline-line" />}
          </div>
          <div className="cn-timeline-content">
            <div className="cn-timeline-header">
              <span className="cn-timeline-title">{item.title}</span>
              {item.timestamp && (
                <span className="cn-timeline-timestamp">{item.timestamp}</span>
              )}
            </div>
            {item.description && (
              <div className="cn-timeline-description">{item.description}</div>
            )}
          </div>
        </div>
      ))}
    </div>
  );
};

Timeline.displayName = 'Timeline';
export default Timeline;

// packages/svelte/src/Timeline.svelte
<script>
  export let items = [];
</script>

<div class="cn-timeline">
  {#each items as item, index}
    <div class="cn-timeline-item {item.variant || 'default'}">
      <div class="cn-timeline-connector">
        <div class="cn-timeline-dot">
          {#if item.icon}{item.icon}{:else}<span class="cn-timeline-dot-inner"></span>{/if}
        </div>
        {#if index < items.length - 1}
          <div class="cn-timeline-line"></div>
        {/if}
      </div>
      <div class="cn-timeline-content">
        <div class="cn-timeline-header">
          <span class="cn-timeline-title">{item.title}</span>
          {#if item.timestamp}
            <span class="cn-timeline-timestamp">{item.timestamp}</span>
          {/if}
        </div>
        {#if item.description}
          <div class="cn-timeline-description">{item.description}</div>
        {/if}
      </div>
    </div>
  {/each}
</div>

<style>
  .cn-timeline { display: flex; flex-direction: column; gap: 0; }
  .cn-timeline-item { display: flex; gap: 12px; position: relative; padding-bottom: 24px; }
  .cn-timeline-connector { display: flex; flex-direction: column; align-items: center; width: 24px; flex-shrink: 0; }
  .cn-timeline-dot { width: 12px; height: 12px; border-radius: 50%; background: #2a2a2a; border: 2px solid #6b2323; z-index: 1; display: flex; align-items: center; justify-content: center; }
  .cn-timeline-dot-inner { width: 6px; height: 6px; border-radius: 50%; background: #6b2323; }
  .cn-timeline-line { width: 2px; flex: 1; background: #2a2a2a; margin-top: 4px; }
  .cn-timeline-item.success .cn-timeline-dot { border-color: #2a6b23; }
  .cn-timeline-item.success .cn-timeline-dot-inner { background: #2a6b23; }
  .cn-timeline-item.warning .cn-timeline-dot { border-color: #6b5a23; }
  .cn-timeline-item.warning .cn-timeline-dot-inner { background: #6b5a23; }
  .cn-timeline-item.error .cn-timeline-dot { border-color: #6b2323; }
  .cn-timeline-item.error .cn-timeline-dot-inner { background: #6b2323; }
  .cn-timeline-item.info .cn-timeline-dot { border-color: #23356b; }
  .cn-timeline-item.info .cn-timeline-dot-inner { background: #23356b; }
  .cn-timeline-content { flex: 1; }
  .cn-timeline-header { display: flex; align-items: baseline; gap: 8px; }
  .cn-timeline-title { font-size: 14px; font-weight: 600; color: #ccc; }
  .cn-timeline-timestamp { font-size: 12px; color: #666; }
  .cn-timeline-description { font-size: 13px; color: #888; margin-top: 4px; }
</style>
