// packages/react/src/components/ai/TokenCounter.tsx
import React from 'react';
import { cn } from '../../utils/cn';

export interface TokenCounterProps {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  maxTokens?: number;
  showBreakdown?: boolean;
  className?: string;
}

export const TokenCounter: React.FC<TokenCounterProps> = ({
  promptTokens = 0,
  completionTokens = 0,
  totalTokens,
  maxTokens,
  showBreakdown = true,
  className,
}) => {
  const total = totalTokens ?? promptTokens + completionTokens;
  const percentage = maxTokens ? Math.min((total / maxTokens) * 100, 100) : null;

  return (
    <div className={cn('cn-token-counter', className)} aria-label={`${total} tokens used`}>
      {percentage !== null && (
        <div className="cn-token-bar">
          <div
            className={cn('cn-token-bar-fill', percentage > 80 && 'cn-token-bar-warning', percentage > 95 && 'cn-token-bar-danger')}
            style={{ width: `${percentage}%` }}
          />
        </div>
      )}
      <div className="cn-token-info">
        <span className="cn-token-total">{total.toLocaleString()} tokens</span>
        {showBreakdown && (
          <span className="cn-token-breakdown">
            ({promptTokens.toLocaleString()} prompt + {completionTokens.toLocaleString()} completion)
          </span>
        )}
        {maxTokens && (
          <span className="cn-token-limit">
            / {maxTokens.toLocaleString()}
          </span>
        )}
      </div>
    </div>
  );
};

// packages/svelte/src/TokenCounter.svelte
<script>
  /** @type {number} */
  export let promptTokens = 0;
  /** @type {number} */
  export let completionTokens = 0;
  /** @type {number|null} */
  export let maxTokens = null;

  $: total = promptTokens + completionTokens;
  $: percentage = maxTokens ? Math.min((total / maxTokens) * 100, 100) : null;
</script>

<div class="cn-token-counter" aria-label="{total} tokens used">
  {#if percentage !== null}
    <div class="cn-token-bar">
      <div
        class="cn-token-bar-fill"
        class:cn-token-bar-warning={percentage > 80}
        class:cn-token-bar-danger={percentage > 95}
        style="width: {percentage}%"
      />
    </div>
  {/if}
  <div class="cn-token-info">
    <span class="cn-token-total">{total.toLocaleString()} tokens</span>
    <span class="cn-token-breakdown">
      ({promptTokens.toLocaleString()} prompt + {completionTokens.toLocaleString()} completion)
    </span>
    {#if maxTokens}
      <span class="cn-token-limit">/ {maxTokens.toLocaleString()}</span>
    {/if}
  </div>
</div>

<style>
  .cn-token-counter { display: flex; flex-direction: column; gap: 4px; }
  .cn-token-bar { height: 4px; background: var(--cn-surface-2); border-radius: 2px; overflow: hidden; }
  .cn-token-bar-fill { height: 100%; background: var(--cn-primary); transition: width 0.3s ease; }
  .cn-token-bar-warning { background: var(--cn-warning); }
  .cn-token-bar-danger { background: var(--cn-error); }
  .cn-token-info { display: flex; align-items: center; gap: 8px; font-size: 12px; }
  .cn-token-total { font-weight: 500; }
  .cn-token-breakdown { color: var(--cn-text-muted); }
</style>
