// packages/svelte/src/CopyButton.svelte
<script>
  /** @type {string} */
  export let text = '';
  /** @type {string} */
  export let label = 'Copy';
  /** @type {string} */
  export let copiedLabel = 'Copied!';
  /** @type {boolean} */
  export let showIcon = true;
  /** @type {number} */
  export let timeout = 2000;

  let copied = false;

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(text);
      copied = true;
      setTimeout(() => { copied = false; }, timeout);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      copied = true;
      setTimeout(() => { copied = false; }, timeout);
    }
  }
</script>

<button
  class="cn-copy-button"
  class:cn-copy-button-copied={copied}
  on:click={handleCopy}
  aria-label={copied ? copiedLabel : label}
>
  {#if showIcon}
    <span class="cn-copy-icon">{copied ? '✓' : '📋'}</span>
  {/if}
  <span class="cn-copy-text">{copied ? copiedLabel : label}</span>
</button>

<style>
  .cn-copy-button {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 12px;
    background: var(--cn-surface);
    border: 1px solid var(--cn-border);
    border-radius: var(--cn-radius);
    cursor: pointer;
    font-size: 13px;
    color: var(--cn-text);
    transition: all 0.15s ease;
  }
  .cn-copy-button:hover { background: var(--cn-surface-2); }
  .cn-copy-button-copied { color: var(--cn-success); border-color: var(--cn-success); }
  .cn-copy-icon { font-size: 14px; }
</style>

// packages/solid/src/components/ai/CopyButton.jsx
import { createSignal, Show } from 'solid-js';

export default function CopyButton(props) {
  const [copied, setCopied] = createSignal(false);
  const [error, setError] = createSignal(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(props.text || '');
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      props.onCopy?.();
    } catch (err) {
      setError(true);
      setTimeout(() => setError(false), 2000);
      props.onError?.(err);
    }
  };

  return (
    <button
      class={`cn-copy-button ${copied() ? 'cn-copy-success' : ''} ${error() ? 'cn-copy-error' : ''}`}
      onClick={handleCopy}
      disabled={props.disabled || !props.text}
      aria-label={copied() ? 'Copied!' : 'Copy to clipboard'}
      title={copied() ? 'Copied!' : 'Copy'}
    >
      <Show when={copied()} fallback={
        <Show when={error()} fallback={
          <span class="cn-copy-icon">⎘</span>
        }>
          <span class="cn-copy-icon">✕</span>
        </Show>
      }>
        <span class="cn-copy-icon">✓</span>
      </Show>

      <style>{`
        .cn-copy-button {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: 4px 8px;
          border-radius: 4px;
          background: transparent;
          border: 1px solid transparent;
          color: var(--cn-text-secondary);
          cursor: pointer;
          transition: all 150ms ease;
        }

        .cn-copy-button:hover:not(:disabled) {
          background: var(--cn-bg-hover);
          border-color: var(--cn-border-default);
        }

        .cn-copy-button:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .cn-copy-icon {
          font-size: 14px;
        }

        .cn-copy-success {
          color: var(--cn-success);
        }

        .cn-copy-error {
          color: var(--cn-error);
        }
      `}</style>
    </button>
  );
}
