// packages/svelte/src/StreamingText.svelte
<script>
  import { afterUpdate, createEventDispatcher } from 'svelte';

  /** @type {string} */
  export let text = '';
  /** @type {number} */
  export let speed = 20;
  /** @type {boolean} */
  export let showCursor = true;

  const dispatch = createEventDispatcher();

  let displayedText = '';
  let isComplete = false;
  let index = 0;
  let prevText = '';

  afterUpdate(() => {
    if (text.length < prevText.length) {
      index = 0;
      displayedText = '';
      isComplete = false;
    }
    prevText = text;
  });

  $: {
    if (text.length > 0 && index < text.length) {
      isComplete = false;
      const chunkSize = Math.max(1, Math.floor(speed / 10));
      const interval = setInterval(() => {
        if (index < text.length) {
          const newIndex = Math.min(index + chunkSize, text.length);
          displayedText = text.slice(0, newIndex);
          index = newIndex;
        } else {
          clearInterval(interval);
          isComplete = true;
          dispatch('complete');
        }
      }, speed);
    } else if (index >= text.length && text.length > 0 && !isComplete) {
      isComplete = true;
      dispatch('complete');
    }
  }
</script>

<div class="cn-streaming-text">
  <span class="cn-streaming-content">{displayedText}</span>
  {#if showCursor && !isComplete}
    <span class="cn-cursor-blink">|</span>
  {/if}
</div>

<style>
  .cn-streaming-text { line-height: 1.6; }
  .cn-streaming-content { white-space: pre-wrap; }
  .cn-cursor-blink { animation: cn-blink 1s step-end infinite; font-weight: 300; }
  @keyframes cn-blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }
</style>

// packages/solid/src/components/ai/StreamingText.jsx
import { createSignal, onMount, onCleanup, createEffect, Show } from 'solid-js';
import CopyButton from './CopyButton';

export default function StreamingText(props) {
  const [displayText, setDisplayText] = createSignal('');
  const [isStreaming, setIsStreaming] = createSignal(false);
  let cursorRef;

  createEffect(() => {
    if (props.text !== undefined && !isStreaming()) {
      setDisplayText(props.text);
    }
  });

  onMount(() => {
    if (props.stream && props.text) {
      startStreaming(props.text);
    }
  });

  const startStreaming = (fullText) => {
    setIsStreaming(true);
    setDisplayText('');
    
    let index = 0;
    const speed = props.speed || 20;
    
    const interval = setInterval(() => {
      if (index < fullText.length) {
        setDisplayText(fullText.slice(0, index + 1));
        index++;
      } else {
        clearInterval(interval);
        setIsStreaming(false);
        props.onStreamEnd?.();
      }
    }, speed);

    onCleanup(() => clearInterval(interval));
  };

  return (
    <div 
      class="cn-streaming-text"
      role="status"
      aria-live="polite"
      aria-label={isStreaming() ? 'Text is streaming' : 'Text display'}
    >
      <div class="cn-streaming-content">
        <span class="cn-streaming-text">{displayText()}</span>
        <Show when={isStreaming()}>
          <span ref={cursorRef} class="cn-streaming-cursor" aria-hidden="true">|</span>
        </Show>
      </div>

      <Show when={!isStreaming() && displayText()}>
        <div class="cn-streaming-actions">
          <CopyButton text={displayText()} />
        </div>
      </Show>

      <style>{`
        .cn-streaming-text {
          position: relative;
        }

        .cn-streaming-content {
          display: inline;
        }

        .cn-streaming-text {
          font-size: 14px;
          line-height: 1.6;
          color: var(--cn-text-primary);
          white-space: pre-wrap;
          word-wrap: break-word;
        }

        .cn-streaming-cursor {
          display: inline-block;
          font-weight: 300;
          animation: cn-blink 1s step-end infinite;
          margin-left: 1px;
        }

        @keyframes cn-blink {
          0%, 50% {
            opacity: 1;
          }
          51%, 100% {
            opacity: 0;
          }
        }

        .cn-streaming-actions {
          display: flex;
          justify-content: flex-end;
          margin-top: 8px;
          opacity: 0;
          transition: opacity 200ms ease;
        }

        .cn-streaming-text:hover .cn-streaming-actions {
          opacity: 1;
        }
      `}</style>
    </div>
  );
}
