// packages/solid/src/components/Button.jsx
import { createSignal, mergeProps } from 'solid-js';

export function Button(props) {
  const merged = mergeProps({ variant: 'default', size: 'md' }, props);
  
  const getClass = () => {
    const classes = ['cn-btn', `cn-btn-${merged.variant}`];
    if (merged.size !== 'md') classes.push(`cn-btn-${merged.size}`);
    if (merged.icon) classes.push('cn-btn-icon');
    return classes.join(' ');
  };

  return (
    <button
      class={getClass()}
      disabled={merged.disabled}
      onClick={merged.onClick}
    >
      {merged.children}
    </button>
  );
}

// packages/react/src/components/Button.jsx
export default function Button({ 
  children, 
  variant = 'default', 
  size = 'md', 
  disabled = false,
  className = '',
  ...props 
}) {
  const variantClass = variant !== 'default' ? `fl-btn-${variant}` : '';
  const sizeClass = size !== 'md' ? `fl-btn-${size}` : '';

  return (
    <button 
      className={`fl-btn ${variantClass} ${sizeClass} ${className}`}
      disabled={disabled}
      {...props}
    >
      {children}
    </button>
  );
}
