// packages/solid/src/components/Checkbox.jsx
import { mergeProps } from 'solid-js';

export function Checkbox(props) {
  const merged = mergeProps({
    checked: false,
    disabled: false,
    onChange: () => {}
  }, props);

  const handleChange = (e) => {
    if (!merged.disabled) {
      merged.onChange(e.target.checked);
    }
  };

  return (
    <label class={`cn-checkbox ${merged.disabled ? 'cn-checkbox-disabled' : ''}`}>
      <input
        type="checkbox"
        class="cn-checkbox-input"
        checked={merged.checked}
        disabled={merged.disabled}
        onChange={handleChange}
      />
      <span class="cn-checkbox-indicator" />
      {merged.label && <span class="cn-checkbox-label">{merged.label}</span>}
    </label>
  );
}

// packages/react/src/components/Checkbox.tsx
import * as React from 'react';

export interface CheckboxProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'checked' | 'onChange'> {
  checked?: boolean;
  onChange?: (checked: boolean) => void;
  label?: React.ReactNode;
}

export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  ({ checked = false, onChange, disabled = false, children, label, className = '', ...props }, ref) => {
    return (
      <label className={`cn-checkbox ${disabled ? 'disabled' : ''} ${className}`.trim()}>
        <input
          ref={ref}
          type="checkbox"
          checked={checked}
          onChange={(e) => onChange?.(e.target.checked)}
          disabled={disabled}
          {...props}
        />
        <span className="cn-checkbox-box" />
        {(label || children) && <span className="cn-checkbox-label">{label || children}</span>}
      </label>
    );
  }
);

Checkbox.displayName = 'Checkbox';

export default Checkbox;
