// packages/solid/src/components/Chip.jsx
import { mergeProps, Show } from 'solid-js';

export function Chip(props) {
  const merged = mergeProps({
    variant: 'default',
    size: 'md',
    selected: false,
    onRemove: null,
    onClick: null,
  }, props);

  return (
    <span
      class={`cn-chip cn-chip-${merged.variant} cn-chip-${merged.size}`}
      classList={{ 'cn-chip-selected': merged.selected }}
      role={merged.onClick ? 'button' : undefined}
      tabindex={merged.onClick ? 0 : undefined}
      onClick={merged.onClick}
    >
      {merged.children}
      <Show when={merged.onRemove}>
        <button
          class="cn-chip-remove"
          onClick={(e) => { e.stopPropagation(); merged.onRemove(); }}
          aria-label="Remove"
        >
          ×
        </button>
      </Show>
    </span>
  );
}

// packages/react/src/components/Chip.tsx
import * as React from 'react';

export interface ChipProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'default' | 'accent' | 'success' | 'warning' | 'error' | 'info';
  size?: 'sm' | 'md' | 'lg';
  selected?: boolean;
  onRemove?: () => void;
  onClick?: () => void;
}

export const Chip: React.FC<ChipProps> = ({
  children,
  variant = 'default',
  size = 'md',
  selected = false,
  onRemove,
  onClick,
  className = '',
  ...props
}) => {
  return (
    <span
      className={`cn-chip cn-chip-${variant} cn-chip-${size} ${selected ? 'cn-chip-selected' : ''} ${className}`.trim()}
      onClick={onClick}
      role={onClick ? 'button' : undefined}
      tabIndex={onClick ? 0 : undefined}
      {...props}
    >
      {children}
      {onRemove && (
        <button
          className="cn-chip-remove"
          onClick={(e) => { e.stopPropagation(); onRemove(); }}
          aria-label="Remove"
        >
          ×
        </button>
      )}
    </span>
  );
};

Chip.displayName = 'Chip';
export default Chip;
