// packages/solid/src/components/Container.jsx
import { mergeProps } from 'solid-js';

export function Container(props) {
  const merged = mergeProps({
    size: 'lg'
  }, props);

  const sizeClasses = {
    sm: 'cn-container-sm',
    md: 'cn-container-md',
    lg: 'cn-container-lg',
    xl: 'cn-container-xl',
    fluid: 'cn-container-fluid'
  };

  return (
    <div class={`cn-container ${sizeClasses[merged.size] || 'cn-container-lg'}`}>
      {merged.children}
    </div>
  );
}

// packages/react/src/components/Container.tsx
import * as React from 'react';

export type ContainerSize = 'sm' | 'md' | 'lg' | 'xl' | 'fluid';

export interface ContainerProps extends React.HTMLAttributes<HTMLDivElement> {
  size?: ContainerSize;
}

export const Container: React.FC<ContainerProps> = ({
  size = 'md',
  children,
  className = '',
  ...props
}) => {
  const sizeClass = size !== 'md' ? `cn-container-${size}` : '';

  return (
    <div className={`cn-container ${sizeClass} ${className}`.trim()} {...props}>
      {children}
    </div>
  );
};

Container.displayName = 'Container';

export default Container;
