// packages/solid/src/components/Modal.jsx
import { mergeProps, Show, createEffect, onCleanup } from 'solid-js';

export function Modal(props) {
  const merged = mergeProps({
    open: false,
    title: '',
    size: 'md',
    onClose: () => {}
  }, props);

  const sizeClasses = {
    sm: 'cn-modal-sm',
    md: 'cn-modal-md',
    lg: 'cn-modal-lg',
    xl: 'cn-modal-xl',
    full: 'cn-modal-full'
  };

  createEffect(() => {
    if (merged.open) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
  });

  onCleanup(() => {
    document.body.style.overflow = '';
  });

  const handleBackdropClick = (e) => {
    if (e.target === e.currentTarget) {
      merged.onClose();
    }
  };

  return (
    <Show when={merged.open}>
      <div class="cn-modal-backdrop" onClick={handleBackdropClick}>
        <div class={`cn-modal ${sizeClasses[merged.size] || 'cn-modal-md'}`}>
          <div class="cn-modal-header">
            <h2 class="cn-modal-title">{merged.title}</h2>
            <button class="cn-modal-close" onClick={merged.onClose}>×</button>
          </div>
          <div class="cn-modal-body">{merged.children}</div>
        </div>
      </div>
    </Show>
  );
}

// packages/react/src/components/Modal.jsx
import { useEffect, useRef } from 'react';

export default function Modal({ 
  isOpen = false, 
  onClose, 
  children,
  className = '' 
}) {
  const modalRef = useRef(null);

  useEffect(() => {
    const handleEscape = (e) => {
      if (e.key === 'Escape' && onClose) {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
      document.body.style.overflow = 'hidden';
    }

    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = '';
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div 
      className={`fl-modal-backdrop fl-modal-open ${className}`}
      onClick={(e) => e.target === e.currentTarget && onClose?.()}
    >
      <div className="fl-modal" ref={modalRef}>
        {children}
      </div>
    </div>
  );
}

Modal.Header = function ModalHeader({ children, onClose, className = '' }) {
  return (
    <div className={`fl-modal-header ${className}`}>
      <div className="fl-modal-title">{children}</div>
      {onClose && (
        <button className="fl-modal-close" onClick={onClose}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
      )}
    </div>
  );
};

Modal.Body = function ModalBody({ children, className = '' }) {
  return <div className={`fl-modal-body ${className}`}>{children}</div>;
};

Modal.Footer = function ModalFooter({ children, className = '' }) {
  return <div className={`fl-modal-footer ${className}`}>{children}</div>;
};
