// packages/solid/src/components/Notification.jsx
import { mergeProps, Show, onCleanup, createEffect } from 'solid-js';

export function Notification(props) {
  const merged = mergeProps({ isOpen: false, variant: 'info', title: '', message: '', duration: 5000, onClose: () => {} }, props);
  createEffect(() => {
    if (merged.isOpen && merged.duration > 0) {
      const timer = setTimeout(() => merged.onClose(), merged.duration);
      onCleanup(() => clearTimeout(timer));
    }
  });
  return (
    <Show when={merged.isOpen}>
      <div class={`cn-notification cn-notification-${merged.variant}`} role="alert">
        <div class="cn-notification-content">
          <Show when={merged.title}><div class="cn-notification-title">{merged.title}</div></Show>
          <div class="cn-notification-message">{merged.message}</div>
        </div>
        <button class="cn-notification-close" onClick={merged.onClose}>×</button>
      </div>
    </Show>
  );
}

// packages/react/src/components/Notification.tsx
import * as React from 'react';

export interface NotificationProps {
  isOpen: boolean;
  onClose: () => void;
  variant?: 'info' | 'success' | 'warning' | 'error';
  title?: string;
  message: string;
  duration?: number;
}

export const Notification: React.FC<NotificationProps> = ({
  isOpen, onClose, variant = 'info', title, message, duration = 5000,
}) => {
  React.useEffect(() => {
    if (isOpen && duration > 0) {
      const timer = setTimeout(onClose, duration);
      return () => clearTimeout(timer);
    }
  }, [isOpen, duration, onClose]);

  if (!isOpen) return null;

  return (
    <div className={`cn-notification cn-notification-${variant}`} role="alert">
      <div className="cn-notification-content">
        {title && <div className="cn-notification-title">{title}</div>}
        <div className="cn-notification-message">{message}</div>
      </div>
      <button className="cn-notification-close" onClick={onClose}>×</button>
    </div>
  );
};

Notification.displayName = 'Notification';
export default Notification;
