// packages/solid/src/components/Stepper.jsx
import { mergeProps, For, createSignal } from 'solid-js';

export function Stepper(props) {
  const merged = mergeProps({ steps: [], currentStep: 0, onStepClick: () => {} }, props);

  return (
    <div class="cn-stepper" role="list" aria-label="Progress">
      <For each={merged.steps}>
        {(step, index) => (
          <div
            class="cn-stepper-step"
            classList={{
              completed: index() < merged.currentStep,
              active: index() === merged.currentStep,
              pending: index() > merged.currentStep,
            }}
            role="listitem"
            aria-current={index() === merged.currentStep ? 'step' : undefined}
            style={{ cursor: merged.onStepClick ? 'pointer' : 'default' }}
            onClick={() => merged.onStepClick(index())}
            onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); merged.onStepClick(index()); } }}
            tabindex={merged.onStepClick ? 0 : undefined}
          >
            <div class="cn-stepper-indicator">
              <span class="cn-stepper-number">
                {index() < merged.currentStep ? '✓' : index() + 1}
              </span>
            </div>
            <div class="cn-stepper-content">
              <div class="cn-stepper-label">{step.label}</div>
              {step.description && (
                <div class="cn-stepper-description">{step.description}</div>
              )}
            </div>
          </div>
        )}
      </For>
    </div>
  );
}

// packages/react/src/components/Stepper.tsx
import * as React from 'react';

export interface StepperStep {
  label: string;
  description?: string;
}

export interface StepperProps extends React.HTMLAttributes<HTMLDivElement> {
  steps: StepperStep[];
  currentStep: number;
  onStepClick?: (step: number) => void;
}

export const Stepper: React.FC<StepperProps> = ({
  steps,
  currentStep,
  onStepClick,
  className = '',
  ...props
}) => {
  return (
    <div className={`cn-stepper ${className}`.trim()} role="list" aria-label="Progress" {...props}>
      {steps.map((step, index) => (
        <div
          key={index}
          className={`cn-stepper-step ${
            index < currentStep ? 'completed' :
            index === currentStep ? 'active' : 'pending'
          }`}
          role="listitem"
          aria-current={index === currentStep ? 'step' : undefined}
          onClick={() => onStepClick?.(index)}
          onKeyDown={(e) => {
            if (onStepClick && (e.key === 'Enter' || e.key === ' ')) {
              e.preventDefault();
              onStepClick(index);
            }
          }}
          tabIndex={onStepClick ? 0 : undefined}
        >
          <div className="cn-stepper-indicator">
            <span className="cn-stepper-number">
              {index < currentStep ? '✓' : index + 1}
            </span>
          </div>
          <div className="cn-stepper-content">
            <div className="cn-stepper-label">{step.label}</div>
            {step.description && (
              <div className="cn-stepper-description">{step.description}</div>
            )}
          </div>
          {index < steps.length - 1 && (
            <div className={`cn-stepper-connector ${index < currentStep ? 'completed' : ''}`} aria-hidden="true" />
          )}
        </div>
      ))}
    </div>
  );
};

Stepper.displayName = 'Stepper';
export default Stepper;
