// packages/solid/src/components/Timeline.jsx
import { mergeProps, For } from 'solid-js';

export function Timeline(props) {
  const merged = mergeProps({ items: [] }, props);

  return (
    <div class="cn-timeline">
      <For each={merged.items}>
        {(item, index) => (
          <div class={`cn-timeline-item ${item.variant || 'default'}`}>
            <div class="cn-timeline-connector">
              <div class="cn-timeline-dot">
                {item.icon || <span class="cn-timeline-dot-inner" />}
              </div>
              {index() < merged.items.length - 1 && <div class="cn-timeline-line" />}
            </div>
            <div class="cn-timeline-content">
              <div class="cn-timeline-header">
                <span class="cn-timeline-title">{item.title}</span>
                {item.timestamp && (
                  <span class="cn-timeline-timestamp">{item.timestamp}</span>
                )}
              </div>
              {item.description && (
                <div class="cn-timeline-description">{item.description}</div>
              )}
            </div>
          </div>
        )}
      </For>
    </div>
  );
}

// packages/react/src/components/Timeline.tsx
import * as React from 'react';

export interface TimelineItem {
  title: string;
  description?: string;
  timestamp?: string;
  icon?: React.ReactNode;
  variant?: 'default' | 'success' | 'warning' | 'error' | 'info';
}

export interface TimelineProps extends React.HTMLAttributes<HTMLDivElement> {
  items: TimelineItem[];
}

export const Timeline: React.FC<TimelineProps> = ({
  items,
  className = '',
  ...props
}) => {
  return (
    <div className={`cn-timeline ${className}`.trim()} {...props}>
      {items.map((item, index) => (
        <div
          key={index}
          className={`cn-timeline-item ${item.variant || 'default'}`}
        >
          <div className="cn-timeline-connector">
            <div className="cn-timeline-dot">
              {item.icon || <span className="cn-timeline-dot-inner" />}
            </div>
            {index < items.length - 1 && <div className="cn-timeline-line" />}
          </div>
          <div className="cn-timeline-content">
            <div className="cn-timeline-header">
              <span className="cn-timeline-title">{item.title}</span>
              {item.timestamp && (
                <span className="cn-timeline-timestamp">{item.timestamp}</span>
              )}
            </div>
            {item.description && (
              <div className="cn-timeline-description">{item.description}</div>
            )}
          </div>
        </div>
      ))}
    </div>
  );
};

Timeline.displayName = 'Timeline';
export default Timeline;
