// packages/react/src/components/Alert.jsx
import { useState } from 'react';

export default function Alert({ 
  type = 'info', 
  title,
  children,
  closable = true,
  onClose,
  className = '' 
}) {
  const [visible, setVisible] = useState(true);

  const handleClose = () => {
    setVisible(false);
    onClose?.();
  };

  if (!visible) return null;

  return (
    <div className={`fl-alert fl-alert-${type} ${className}`}>
      <div className="fl-alert-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          {type === 'success' && <polyline points="20 6 9 17 4 12"></polyline>}
          {type === 'error' && (
            <>
              <circle cx="12" cy="12" r="10"></circle>
              <line x1="15" y1="9" x2="9" y2="15"></line>
              <line x1="9" y1="9" x2="15" y2="15"></line>
            </>
          )}
          {type === 'warning' && (
            <>
              <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
              <line x1="12" y1="9" x2="12" y2="13"></line>
              <line x1="12" y1="17" x2="12.01" y2="17"></line>
            </>
          )}
          {type === 'info' && (
            <>
              <circle cx="12" cy="12" r="10"></circle>
              <line x1="12" y1="16" x2="12" y2="12"></line>
              <line x1="12" y1="8" x2="12.01" y2="8"></line>
            </>
          )}
        </svg>
      </div>
      <div className="fl-alert-content">
        {title && <div className="fl-alert-title">{title}</div>}
        <div className="fl-alert-message">{children}</div>
      </div>
      {closable && (
        <button className="fl-alert-close" onClick={handleClose}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
      )}
    </div>
  );
}

// packages/solid/src/components/Alert.jsx
import { mergeProps, Show } from 'solid-js';

export function Alert(props) {
  const merged = mergeProps({
    title: '',
    message: '',
    variant: 'info',
    dismissible: false,
    onClose: () => {}
  }, props);

  const variantIcons = {
    info: 'ℹ',
    success: '✓',
    warning: '⚠',
    error: '✕'
  };

  return (
    <div class={`cn-alert cn-alert-${merged.variant}`}>
      <span class="cn-alert-icon">{variantIcons[merged.variant]}</span>
      <div class="cn-alert-content">
        <Show when={merged.title}>
          <h4 class="cn-alert-title">{merged.title}</h4>
        </Show>
        <Show when={merged.message}>
          <p class="cn-alert-message">{merged.message}</p>
        </Show>
      </div>
      <Show when={merged.dismissible}>
        <button class="cn-alert-close" onClick={merged.onClose}>×</button>
      </Show>
    </div>
  );
}
