// packages/react/src/components/DatePicker.tsx
import * as React from 'react';

export interface DatePickerProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange'> {
  value?: string;
  onChange?: (date: string) => void;
  minDate?: string;
  maxDate?: string;
  format?: string;
}

export const DatePicker: React.FC<DatePickerProps> = ({
  value = '',
  onChange,
  minDate,
  maxDate,
  format = 'YYYY-MM-DD',
  className = '',
  ...props
}) => {
  return (
    <div className={`cn-datepicker ${className}`.trim()}>
      <input
        type="date"
        className="cn-datepicker-input"
        value={value}
        onChange={(e) => onChange?.(e.target.value)}
        min={minDate}
        max={maxDate}
        {...props}
      />
    </div>
  );
};

DatePicker.displayName = 'DatePicker';
export default DatePicker;

// packages/solid/src/components/DatePicker.jsx
import { mergeProps } from 'solid-js';

export function DatePicker(props) {
  const merged = mergeProps({ value: '', minDate: '', maxDate: '', disabled: false, onChange: () => {} }, props);

  return (
    <div class="cn-datepicker">
      <input
        type="date"
        class="cn-datepicker-input"
        value={merged.value}
        min={merged.minDate}
        max={merged.maxDate}
        disabled={merged.disabled}
        onChange={(e) => merged.onChange(e.target.value)}
      />
    </div>
  );
}
