// packages/react/src/components/Drawer.tsx
import * as React from 'react';
import { createPortal } from 'react-dom';

export interface DrawerProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  children: React.ReactNode;
  side?: 'left' | 'right' | 'top' | 'bottom';
  size?: 'sm' | 'md' | 'lg';
}

export const Drawer: React.FC<DrawerProps> = ({
  isOpen,
  onClose,
  title,
  children,
  side = 'right',
  size = 'md',
}) => {
  if (!isOpen) return null;

  return createPortal(
    <div className="cn-drawer-overlay" onClick={onClose}>
      <div
        className={`cn-drawer cn-drawer-${side} cn-drawer-${size}`}
        onClick={(e) => e.stopPropagation()}
      >
        {title && (
          <div className="cn-drawer-header">
            <h3 className="cn-drawer-title">{title}</h3>
            <button className="cn-drawer-close" onClick={onClose}>×</button>
          </div>
        )}
        <div className="cn-drawer-body">{children}</div>
      </div>
    </div>,
    document.body
  );
};

Drawer.displayName = 'Drawer';
export default Drawer;

// packages/solid/src/components/Drawer.jsx
import { mergeProps, Show } from 'solid-js';

export function Drawer(props) {
  const merged = mergeProps({
    isOpen: false,
    title: '',
    side: 'right',
    size: 'md',
    onClose: () => {},
  }, props);

  return (
    <Show when={merged.isOpen}>
      <div class="cn-drawer-overlay" onClick={merged.onClose}>
        <div
          class={`cn-drawer cn-drawer-${merged.side} cn-drawer-${merged.size}`}
          onClick={(e) => e.stopPropagation()}
        >
          <Show when={merged.title}>
            <div class="cn-drawer-header">
              <h3 class="cn-drawer-title">{merged.title}</h3>
              <button class="cn-drawer-close" onClick={merged.onClose}>×</button>
            </div>
          </Show>
          <div class="cn-drawer-body">{merged.children}</div>
        </div>
      </div>
    </Show>
  );
}
