// packages/react/src/components/EmptyState.tsx
import * as React from 'react';

export interface EmptyStateProps extends React.HTMLAttributes<HTMLDivElement> {
  icon?: React.ReactNode;
  title: string;
  description?: string;
  action?: React.ReactNode;
}

export const EmptyState: React.FC<EmptyStateProps> = ({ icon, title, description, action, className = '', ...props }) => {
  return (
    <div className={`cn-empty-state ${className}`.trim()} {...props}>
      {icon && <div className="cn-empty-state-icon">{icon}</div>}
      <div className="cn-empty-state-title">{title}</div>
      {description && <div className="cn-empty-state-description">{description}</div>}
      {action && <div className="cn-empty-state-action">{action}</div>}
    </div>
  );
};

EmptyState.displayName = 'EmptyState';
export default EmptyState;

// packages/solid/src/components/EmptyState.jsx
import { mergeProps, Show } from 'solid-js';

export function EmptyState(props) {
  const merged = mergeProps({ title: '', description: '', icon: null }, props);
  return (
    <div class="cn-empty-state">
      <Show when={merged.icon}>
        <div class="cn-empty-state-icon">{merged.icon}</div>
      </Show>
      <div class="cn-empty-state-title">{merged.title}</div>
      <Show when={merged.description}>
        <div class="cn-empty-state-description">{merged.description}</div>
      </Show>
      <Show when={merged.children}>
        <div class="cn-empty-state-action">{merged.children}</div>
      </Show>
    </div>
  );
}
