// packages/react/src/components/Popover.tsx
import * as React from 'react';

export interface PopoverProps {
  trigger: React.ReactNode;
  children: React.ReactNode;
  placement?: 'top' | 'bottom' | 'left' | 'right';
  isOpen?: boolean;
  onToggle?: (open: boolean) => void;
}

export const Popover: React.FC<PopoverProps> = ({
  trigger,
  children,
  placement = 'bottom',
  isOpen: controlledOpen,
  onToggle,
}) => {
  const [internalOpen, setInternalOpen] = React.useState(false);
  const open = controlledOpen ?? internalOpen;
  const setOpen = onToggle ?? setInternalOpen;

  return (
    <div className={`cn-popover-wrapper cn-popover-${placement}`}>
      <div className="cn-popover-trigger" onClick={() => setOpen(!open)}>
        {trigger}
      </div>
      {open && (
        <div className="cn-popover-content">
          {children}
        </div>
      )}
    </div>
  );
};

Popover.displayName = 'Popover';
export default Popover;

// packages/solid/src/components/Popover.jsx
import { mergeProps, createSignal, Show } from 'solid-js';

export function Popover(props) {
  const merged = mergeProps({
    trigger: null,
    placement: 'bottom',
    isOpen: undefined,
    onToggle: null,
  }, props);

  const [internalOpen, setInternalOpen] = createSignal(false);
  const open = () => merged.isOpen !== undefined ? merged.isOpen : internalOpen();
  const setOpen = merged.onToggle || setInternalOpen;

  return (
    <div class={`cn-popover-wrapper cn-popover-${merged.placement}`}>
      <div class="cn-popover-trigger" onClick={() => setOpen(!open())}>
        {merged.trigger}
      </div>
      <Show when={open()}>
        <div class="cn-popover-content">
          {merged.children}
        </div>
      </Show>
    </div>
  );
}
