// packages/react/src/components/Progress.tsx
import * as React from 'react';

export type ProgressVariant = 'default' | 'success' | 'warning' | 'error';
export type ProgressSize = 'sm' | 'md' | 'lg';

export interface ProgressProps extends React.HTMLAttributes<HTMLDivElement> {
  value?: number;
  max?: number;
  showLabel?: boolean;
  variant?: ProgressVariant;
  size?: ProgressSize;
}

export const Progress: React.FC<ProgressProps> = ({
  value = 0,
  max = 100,
  showLabel = false,
  variant = 'default',
  size = 'md',
  className = '',
  ...props
}) => {
  const percentage = Math.min(Math.max((value / max) * 100, 0), 100);

  return (
    <div className={className} {...props}>
      {showLabel && (
        <div className="cn-progress-label">
          <span>{percentage.toFixed(0)}%</span>
        </div>
      )}
      <div
        className={`cn-progress ${size !== 'md' ? `cn-progress-${size}` : ''} ${variant !== 'default' ? `cn-progress-${variant}` : ''}`.trim()}
        role="progressbar"
        aria-valuenow={value}
        aria-valuemin={0}
        aria-valuemax={max}
      >
        <div className="cn-progress-bar" style={{ width: `${percentage}%` }} />
      </div>
    </div>
  );
};

Progress.displayName = 'Progress';

export default Progress;

// packages/solid/src/components/Progress.jsx
import { mergeProps, Show } from 'solid-js';

export function Progress(props) {
  const merged = mergeProps({
    value: 0,
    max: 100,
    variant: 'default',
    size: 'md',
    showLabel: false
  }, props);

  const percentage = () => {
    return Math.min(Math.max((merged.value / merged.max) * 100, 0), 100);
  };

  const sizeClasses = {
    sm: 'cn-progress-sm',
    md: 'cn-progress-md',
    lg: 'cn-progress-lg'
  };

  return (
    <div class={`cn-progress ${sizeClasses[merged.size] || 'cn-progress-md'}`}>
      <div class="cn-progress-track">
        <div
          class={`cn-progress-bar cn-progress-${merged.variant}`}
          style={`width: ${percentage()}%`}
        />
      </div>
      <Show when={merged.showLabel}>
        <span class="cn-progress-label">{Math.round(percentage())}%</span>
      </Show>
    </div>
  );
}
