// packages/react/src/components/Slider.tsx
import * as React from 'react';

export interface SliderProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'value' | 'onChange'> {
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  onChange?: (value: number) => void;
}

export const Slider = React.forwardRef<HTMLInputElement, SliderProps>(
  ({ value = 0, min = 0, max = 100, step = 1, onChange, disabled = false, className = '', ...props }, ref) => {
    return (
      <input
        ref={ref}
        type="range"
        className={`cn-slider ${className}`.trim()}
        value={value}
        min={min}
        max={max}
        step={step}
        onChange={(e) => onChange?.(Number(e.target.value))}
        disabled={disabled}
        {...props}
      />
    );
  }
);

Slider.displayName = 'Slider';

export default Slider;

// packages/solid/src/components/Slider.jsx
import { mergeProps } from 'solid-js';

export function Slider(props) {
  const merged = mergeProps({
    min: 0,
    max: 100,
    value: 0,
    step: 1,
    disabled: false,
    onInput: () => {}
  }, props);

  const percentage = () => {
    return ((merged.value - merged.min) / (merged.max - merged.min)) * 100;
  };

  return (
    <div class={`cn-slider ${merged.disabled ? 'cn-slider-disabled' : ''}`}>
      <input
        type="range"
        class="cn-slider-input"
        min={merged.min}
        max={merged.max}
        value={merged.value}
        step={merged.step}
        disabled={merged.disabled}
        onInput={(e) => merged.onInput?.(parseFloat(e.target.value))}
      />
      <div class="cn-slider-track">
        <div class="cn-slider-fill" style={`width: ${percentage()}%`} />
      </div>
    </div>
  );
}
