// packages/react/src/components/Tabs.jsx
import { useState } from 'react';

export default function Tabs({ 
  defaultIndex = 0, 
  index: controlledIndex, 
  onChange, 
  children,
  className = '' 
}) {
  const [internalIndex, setInternalIndex] = useState(defaultIndex);
  const activeIndex = controlledIndex !== undefined ? controlledIndex : internalIndex;

  const handleTabClick = (idx) => {
    if (onChange) {
      onChange(idx);
    } else {
      setInternalIndex(idx);
    }
  };

  const tabs = [];
  const panels = [];

  children.forEach((child) => {
    if (child.type?.displayName === 'Tab') {
      tabs.push(child);
    } else if (child.type?.displayName === 'TabPanel') {
      panels.push(child);
    }
  });

  return (
    <div className={className}>
      <div className="fl-tabs">
        {tabs.map((tab, idx) => (
          <div
            key={idx}
            className={`fl-tab ${activeIndex === idx ? 'fl-tab-active' : ''}`}
            onClick={() => handleTabClick(idx)}
          >
            {tab.props.children}
          </div>
        ))}
      </div>
      {panels.map((panel, idx) => (
        <div
          key={idx}
          className={`fl-tab-panel ${activeIndex === idx ? 'fl-tab-panel-active' : ''}`}
        >
          {panel.props.children}
        </div>
      ))}
    </div>
  );
}

export function Tab({ children }) {
  return children;
}
Tab.displayName = 'Tab';

export function TabPanel({ children }) {
  return children;
}
TabPanel.displayName = 'TabPanel';

// packages/solid/src/components/Tabs.jsx
import { mergeProps, For } from 'solid-js';

export function Tabs(props) {
  const merged = mergeProps({
    tabs: [],
    activeIndex: 0,
    onChange: () => {}
  }, props);

  const handleTabClick = (index) => {
    merged.onChange(index);
  };

  const activeTab = () => {
    return merged.tabs[merged.activeIndex];
  };

  return (
    <div class="cn-tabs">
      <div class="cn-tabs-list">
        <For each={merged.tabs}>{(tab, index) => (
          <button
            type="button"
            class={`cn-tabs-tab ${index() === merged.activeIndex ? 'cn-tabs-tab-active' : ''}`}
            onClick={() => handleTabClick(index())}
          >
            {tab.label || tab}
          </button>
        )}</For>
      </div>
      <div class="cn-tabs-panel">
        {activeTab()?.content || merged.children}
      </div>
    </div>
  );
}
