// packages/react/src/components/Tooltip.tsx
import * as React from 'react';

export type TooltipPosition = 'top' | 'bottom' | 'left' | 'right';

export interface TooltipProps {
  children?: React.ReactNode;
  content: React.ReactNode;
  position?: TooltipPosition;
  className?: string;
}

export const Tooltip: React.FC<TooltipProps> = ({
  children,
  content,
  position = 'top',
  className = '',
}) => {
  const positionClass = position !== 'top' ? `cn-tooltip-${position}` : '';
  const tooltipId = React.useId();

  return (
    <div className={`cn-tooltip ${positionClass} ${className}`.trim()}>
      <span aria-describedby={tooltipId}>{children}</span>
      <div className="cn-tooltip-content" id={tooltipId} role="tooltip">
        {content}
      </div>
    </div>
  );
};

Tooltip.displayName = 'Tooltip';

export default Tooltip;

// packages/solid/src/components/Tooltip.jsx
import { mergeProps, createSignal, Show, createUniqueId } from 'solid-js';

export function Tooltip(props) {
  const merged = mergeProps({
    content: '',
    position: 'top'
  }, props);

  const [isVisible, setIsVisible] = createSignal(false);
  const tooltipId = createUniqueId();

  const positionClasses = {
    top: 'cn-tooltip-top',
    bottom: 'cn-tooltip-bottom',
    left: 'cn-tooltip-left',
    right: 'cn-tooltip-right'
  };

  return (
    <div
      class="cn-tooltip-wrapper"
      onMouseEnter={() => setIsVisible(true)}
      onMouseLeave={() => setIsVisible(false)}
    >
      <span aria-describedby={tooltipId}>{merged.children}</span>
      <Show when={isVisible()}>
        <div class={`cn-tooltip ${positionClasses[merged.position] || 'cn-tooltip-top'}`} id={tooltipId} role="tooltip">
          {merged.content}
        </div>
      </Show>
    </div>
  );
}

export default Tooltip;
