// packages/solid/src/components/ai/RAGReference.jsx
import { createSignal, For, Show } from 'solid-js';

export function RAGReference(props) {
  const [expanded, setExpanded] = createSignal(!props.expandable);

  const references = () => props.references || [];

  return (
    <Show when={references().length > 0}>
      <div class={props.className ? `cn-rag-reference ${props.className}` : 'cn-rag-reference'}>
        <Show when={props.expandable}>
          <button
            class="cn-rag-toggle"
            onClick={() => setExpanded(!expanded())}
            aria-expanded={expanded()}
          >
            📚 Sources ({references().length})
            <span class="cn-rag-chevron">{expanded() ? '▲' : '▼'}</span>
          </button>
        </Show>

        <Show when={expanded()}>
          <div class="cn-rag-list">
            <For each={references()}>
              {(ref) => (
                <div class="cn-rag-item">
                  <div class="cn-rag-item-header">
                    <span class="cn-rag-item-title">{ref.title}</span>
                    <span class="cn-rag-item-source">{ref.source}</span>
                    <Show when={ref.score !== undefined}>
                      <span class="cn-rag-item-score">
                        {Math.round(ref.score * 100)}% match
                      </span>
                    </Show>
                  </div>
                  <div class="cn-rag-item-snippet">{ref.snippet}</div>
                  <Show when={ref.url}>
                    <a
                      class="cn-rag-item-link"
                      href={ref.url}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      View source →
                    </a>
                  </Show>
                </div>
              )}
            </For>
          </div>
        </Show>
      </div>
    </Show>
  );
}

// packages/react/src/components/ai/RAGReference.tsx
import React, { useState } from 'react';
import { cn } from '../../utils/cn';

export interface Reference {
  id: string;
  title: string;
  source: string;
  snippet: string;
  url?: string;
  score?: number;
}

export interface RAGReferenceProps {
  references: Reference[];
  expandable?: boolean;
  className?: string;
}

export const RAGReference: React.FC<RAGReferenceProps> = ({
  references,
  expandable = true,
  className,
}) => {
  const [expanded, setExpanded] = useState(!expandable);

  if (references.length === 0) return null;

  return (
    <div className={cn('cn-rag-reference', className)}>
      {expandable && (
        <button
          className="cn-rag-toggle"
          onClick={() => setExpanded(!expanded)}
          aria-expanded={expanded}
        >
          📚 Sources ({references.length})
          <span className="cn-rag-chevron">{expanded ? '▲' : '▼'}</span>
        </button>
      )}

      {expanded && (
        <div className="cn-rag-list">
          {references.map((ref) => (
            <div key={ref.id} className="cn-rag-item">
              <div className="cn-rag-item-header">
                <span className="cn-rag-item-title">{ref.title}</span>
                <span className="cn-rag-item-source">{ref.source}</span>
                {ref.score !== undefined && (
                  <span className="cn-rag-item-score">
                    {Math.round(ref.score * 100)}% match
                  </span>
                )}
              </div>
              <div className="cn-rag-item-snippet">{ref.snippet}</div>
              {ref.url && (
                <a
                  className="cn-rag-item-link"
                  href={ref.url}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  View source →
                </a>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
